// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Lab11 {
	
	
	public partial class UpdateCar {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox Model;
		
		protected System.Web.UI.WebControls.TextBox Power;
		
		protected System.Web.UI.WebControls.TextBox Fuel;
		
		protected System.Web.UI.WebControls.TextBox Price;
		
		protected System.Web.UI.WebControls.TextBox Color;
		
		protected System.Web.UI.WebControls.TextBox Year;
		
		protected System.Web.UI.WebControls.Button UpdateCarButton;
	}
}
